### ISSUE TITLE
Use dokku-daemon

### ISSUE THREAD

**Issue by josegonzalez** [beydogan/dokku-man#7]
Just going to leave this here: https://github.com/dokku/dokku-daemon

**Comment by beydogan** [comment]
Hi @josegonzalez, thanks for the link, I haven't seen dokku-daemon before. It would make this easier, I will look into it.

**Comment by josegonzalez** [comment]
I use it internally at work to trigger `dokku run` commands for the purposes of build deployments.

**Comment by beydogan** [comment]
@josegonzalez do you have any plans to create another plugin or app for creating an HTTP API endpoint to execute commands on dokku-daemon? It might make things more easy. If you dont have plans I might work on it.

**Comment by josegonzalez** [comment]
My plans for the forceable future do not involve any work on non-dokku core projects.

**Comment by beydogan** [comment]
Instead of using dokku-daemon, DokkuMan will interact with https://github.com/beydogan/dokku-api
